### ISSUE TITLE
CHM file doesn't work.

### ISSUE THREAD

**Issue by Chris2011** [kshahar/launchysharp#1]
Hi,

today I wanted to create a plugin with Launchy# so I took the SimplePlugin#, created a Class Lib and builded it. I copied the 2 dll's so my lib and Launchy#API.dll to launchy and  restart it but I couldn't see anything. My plugin doesn't have an entry inside the plugin area inside launchy. Ok so I wanted to take a look inside the CHM file but it doesn't show my anything. Is it a problem with the chm (maybe corrupt) file or smth else?

Cheers,

Chris

**Comment by kshahar** [comment]
It's is a Windows feature. CHM files cannot be displayed if they were downloaded from the internet, unless you unblock them as [discussed on stackoverflow](http://stackoverflow.com/questions/3617189/cannot-open-chm-file-gives-page-cannot-be-displayed-error):

```
Right click on the file, click properties, and click unblock.
```

Regarding the other issues, follow the instructions on the main page: https://github.com/kshahar/launchysharp
In particular, your plugin DLL should be placed in the 'plugins' directory of Launchy.

**Comment by Chris2011** [comment]
Thx, on an other machine it works, I will test it later on my main machine.

**Comment by Chris2011** [comment]
I copied the file in an other folder, that works for me. Thx.
