### ISSUE TITLE
Launchy crashes with LaunchySharpPlugin.dll

### ISSUE THREAD

**Issue by Chris2011** [kshahar/launchysharp#2]
As related to this problem: http://sourceforge.net/p/launchysharp/discussion/903447/thread/d740ec4b/

when I copy the LaunchySharpPlugin.dll into the plugin folder, without smth else, Launchy crashs. Not only once, twice, it crashs always. I use The stable version of Launchy 2.5 and the Launchy# 1.1.1, date is 2009-03-07.

Cheers,

Chris

**Comment by kshahar** [comment]
To install Launchy# download "Launchy#-1.1.1-Bin.zip" and follow the instructions:

```
Extract this file in the main Launchy directory (e.g. C:\Program Files\Launchy).
```

The link and instructions are on the main page: https://github.com/kshahar/launchysharp.

**Comment by Chris2011** [comment]
Yeah, I missed that thing with ...in the main Launchy dir... :). Works on an other machine, I will test it later on my main machine. Thx.

**Comment by Chris2011** [comment]
Works now, Thx.
