### ISSUE TITLE
Can't create plugin.

### ISSUE THREAD

**Issue by Chris2011** [kshahar/launchysharp#3]
As I did some research on your Simple Plugin, GoY your little Readme.md and took a look at the CHM file (Only a reference for the methods/props, nothing more) I can't get my plugin working. At the end I copied the code from the SimplePlugin#.cs into my class lib, not errors, clean and build is always ok (copied into launchy, nothing happens), rewrite the batch file and got the dll again, smaller one, copied into the Launchy\plugin folder, restart launchy. All files from Launchy# are correctly copied into Launchy folder. Nothing happens, no options entry, I think it will not be initialized. I don't get it. I thought my start to write a simple plugin was ok but I think here is missing smth. Is there a start guide which I havn't found yet or did I miss smth?

Regards

Chris

**Comment by kshahar** [comment]
I've tested on several machines (Windows 7 32/64 bit) and there doesn't seem to be any issue with Launchy#. Try to install the Go-Y# plugin available from the main project page to see if there's any issue with your installation. Also, please upload a minimal example to reproduce this issue as I can't seem to reproduce it on my side.
